name: Aegis
main: com.aegis.Aegis
version: ${project.version}-${git.commit.id.abbrev}
api-version: '1.21'
author: CalamityCats
website: https://modrinth.com/
commands:
  aegis:
    description: Aegis AntiCheat command
    usage: /aegis alerts|reload|vl <player>
    permission: aegis.command
permissions:
  aegis.command:
    default: op
depend:
  - packetevents
